name: Release pfQuest-epoch on changes
on:
  push:
    branches: [ main ]
    paths:
      - 'pfQuest-epoch/**'
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Zip pfQuest-epoch folder
        run: zip -r pfQuest-epoch.zip pfQuest-epoch

      - name: Create Versioned Release and Upload Asset
        uses: softprops/action-gh-release@v2
        with:
          # Use a dynamic tag based on the run number
          tag_name: pfQuest-epoch-${{ github.run_number }}
          name: Release pfQuest-epoch-${{ github.run_number }}
          files: pfQuest-epoch.zip
          # Set the 'latest' flag on this release
          latest: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
